name: SPICA Assemble Debug

on:
  workflow_dispatch:

jobs:
  assemble:
    name: Assemble Debug APK
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # ✅ Step 1: Compile common sources and show errors clearly
      - name: Compile Common Metadata (Error Highlighter)
        run: |
          echo "🔍 Compiling commonMain to detect Kotlin errors..."
          ./gradlew compileKotlinMetadata --stacktrace --info --warning-mode all 2>&1 | tee compile_log.txt

          # Show Kotlin errors with a few lines of context
          $errors = Select-String -Path compile_log.txt -Pattern "e: " -Context 2,2
          if ($errors) {
            echo ""
            echo "❌ Kotlin Compilation Errors Found:"
            echo "----------------------------------"
            $errors | ForEach-Object {
              echo "----------------------------------"
              $_.Context.PreContext
              echo $_.Line
              $_.Context.PostContext
            }
            echo "----------------------------------"
            exit 1
          } else {
            echo "✅ No Kotlin compilation errors in commonMain."
          }
        shell: pwsh

      # ✅ Step 2: Assemble APK (only runs if step above passes)
      - name: Assemble Android Debug APK
        run: ./gradlew :composeApp:assembleDebug --stacktrace --info --warning-mode all
        shell: bash

      # 📦 Step 3: Upload generated APK (optional)
      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SPICA-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
