name: SPICA Assemble Debug (Fast Cache Build)

on:
  workflow_dispatch:

jobs:
  assemble:
    name: Assemble Debug APK (With Build Cache)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🧱 Cache Gradle wrapper, config, and build caches
      - name: Cache Gradle files + Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle/build-cache
            composeApp/build
            shared/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('gradle.properties', '**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # ✅ Compile commonMain sources for early Kotlin errors
      - name: Compile Kotlin Metadata (Error Extractor)
        id: compile_metadata
        shell: bash
        run: |
          echo "🔍 Compiling commonMain sources to detect Kotlin errors..."
          ./gradlew compileKotlinMetadata --build-cache --stacktrace --info | tee build_log.txt

          echo ""
          echo "----------------------------------------"
          echo "🧾 CommonMain Kotlin Compilation Error Summary"
          echo "----------------------------------------"
          grep -E "^e: " build_log.txt || echo "✅ No Kotlin compilation errors found in commonMain."

      # 🚀 Assemble Android Debug APK
      - name: Assemble Android Debug APK (Error Extractor)
        id: assemble_debug
        shell: bash
        run: |
          echo "🚀 Building Android Debug APK..."
          ./gradlew :composeApp:assembleDebug --build-cache --stacktrace --info | tee android_build_log.txt

          echo ""
          echo "----------------------------------------"
          echo "🤖 Android Kotlin Compilation Error Summary"
          echo "----------------------------------------"
          grep -E "^e: " android_build_log.txt || echo "✅ No Kotlin compilation errors found in Android module."

      # 📦 Upload APK if successful
      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SPICA-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
