name: Kotlin Multiplatform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      # ✅ Compile common, JVM/Android, JS
      - name: Compile JVM/JS/Common
        run: |
          ./gradlew compileKotlinMetadata \
                   compileKotlinJvm \
                   compileKotlinJs \
                   --stacktrace --warning-mode all

      - name: Full build (Linux)
        run: ./gradlew build --stacktrace --warning-mode all

      - name: Run checks (Linux)
        run: ./gradlew check --stacktrace --warning-mode all

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      # ✅ Compile iOS targets (needs Xcode, so macOS only)
      - name: Compile iOS
        run: |
          ./gradlew compileKotlinIosArm64 \
                   compileKotlinIosX64 \
                   compileKotlinIosSimulatorArm64 \
                   --stacktrace --warning-mode all

      - name: Full build (macOS)
        run: ./gradlew build --stacktrace --warning-mode all

      - name: Run checks (macOS)
        run: ./gradlew check --stacktrace --warning-mode all
