name: Kotlin Multiplatform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      # Windows doesn’t care about chmod, but it helps cross-platform
      - name: Make gradlew executable
        run: chmod +x gradlew
        shell: bash

      # ✅ Compile common, JVM, and JS sources
      - name: Compile JVM/JS/Common
        run: |
          ./gradlew compileKotlinMetadata ^
                   --stacktrace --warning-mode all
        shell: cmd

      # ✅ Assemble Android debug APK
      - name: Assemble Debug (Android)
        run: ./gradlew assembleDebug --stacktrace --warning-mode all
        shell: cmd

      # ✅ Run full build
      - name: Full build
        run: ./gradlew build --stacktrace --warning-mode all
        shell: cmd

      # ✅ Run checks (tests, lint, etc.)
      - name: Run checks
        run: ./gradlew check --stacktrace --warning-mode all
        shell: cmd
