name: SPICA Build & Test (With Cache)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Test (KMP)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🧱 Cache Gradle wrapper, config, and build caches
      - name: Cache Gradle & Build Files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/.gradle/build-cache
            composeApp/build
            shared/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # ⚙️ Build all KMP targets (with configuration cache + build cache)
      - name: Build all KMP targets
        run: ./gradlew build --configuration-cache --build-cache --stacktrace --info
        shell: bash

      # 🚀 Assemble Android Debug APK
      - name: Assemble Android Debug APK
        run: ./gradlew :composeApp:assembleDebug --configuration-cache --build-cache --stacktrace --info
        shell: bash

      # 🧪 Run all tests
      - name: Run Tests
        run: ./gradlew test --configuration-cache --build-cache --stacktrace --info
        shell: bash

      # 📦 Upload Debug APK (optional)
      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SPICA-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
